server.port=8080

# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://tanmayikulkarni:Tanmayi@cluster0.ji6zlgg.mongodb.net/LocalLink?retryWrites=true&w=majority
spring.data.mongodb.database=LocalLink

# Detailed Debugging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.localmart=TRACE
server.error.include-message=always
server.error.include-stacktrace=always
